# Generated by Django 5.0.1 on 2024-01-15 03:31

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Freeway',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField(default='Catalina Island')),
                ('start_coordinates', models.TextField(default='33.34281 -118.32785')),
                ('end_coordinates', models.TextField(default='33.34281 -118.32785')),
            ],
        ),
        migrations.CreateModel(
            name='TrafficCondition',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('description', models.TextField(default='unknown')),
            ],
        ),
        migrations.CreateModel(
            name='Junctions',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField(null=True)),
                ('coordinates', models.TextField(default='33.34281 -118.32785')),
                ('cardinal_bound', models.TextField(null=True)),
                ('fk_point_a', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='junction_a_freeway', to='horoscope.freeway')),
                ('fk_point_b', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='junction_b_freeway', to='horoscope.freeway')),
            ],
        ),
        migrations.CreateModel(
            name='TrafficChart',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('date_hour', models.DateTimeField(default=datetime.datetime.now)),
                ('fk_point_a', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='traffic_a_freeway', to='horoscope.freeway')),
                ('fk_point_b', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='traffic_b_freeway', to='horoscope.freeway')),
                ('traffic_condition', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='traffic_condition', to='horoscope.trafficcondition')),
            ],
        ),
    ]
