# Generated by Django 5.0.1 on 2024-01-16 00:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("horoscope", "0003_rename_junctionexit_junction"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="TrafficChart",
            new_name="Traffic",
        ),
    ]
