# Generated by Django 5.0.1 on 2024-01-20 04:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("horoscope", "0004_rename_trafficchart_traffic"),
    ]

    operations = [
        migrations.AddField(
            model_name="freeway",
            name="alternate_names",
            field=models.JSONField(null=True),
        ),
    ]
