# Generated by Django 5.0.1 on 2024-01-21 05:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("horoscope", "0005_freeway_alternate_names"),
    ]

    operations = [
        migrations.AlterField(
            model_name="freeway",
            name="alternate_names",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
